# Generated by Django 3.2.15 on 2022-10-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='new_file',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
